# Connection Details
url=jdbc:postgresql://172.17.0.1:5432/migration_tool
username=postgres
password=postgres

# Changelog Configuration
changeLogFile=changelog-master.yaml

#defaultSchemaName=

# log Config
liquibase.logFormat=JSON
liquibase.logLevel=FINE
# Point this to an absolute path inside the container (Paid version)
# liquibase.logFile=/liquibase/logs/liquibase-structured.log